services:
  cangkang-web:
    container_name: raditya_web
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    restart: unless-stopped

    # volumes:
    #   - ./dist:/usr/share/nginx/html:ro
    #   - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
